# frozen_string_literal: true

source "https://rubygems.org"

gem 'exp_backoff', path: '../' # for test in localhost
# gem "exp_backoff", git: "git@github.com:solehudinmq/exp_backoff.git", branch: "main"
gem "byebug"
